# Generated by Django 4.1.3 on 2022-11-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('student_id', models.CharField(max_length=12, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('is_vaccined', models.CharField(choices=[('FULL', 'Fully Vaccinated'), ('FIRSTDOSE', 'First Dose'), ('NEVER', 'Never')], default='FULL', max_length=50)),
                ('is_boostered', models.CharField(choices=[('FULL', 'Fully Boostered'), ('FIRSTBOOST', 'First Boost'), ('NEVER', 'Never')], default='NEVER', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('symptoms', models.CharField(max_length=1000, null=True)),
                ('diagnosis', models.CharField(max_length=500, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heronsafe.student')),
            ],
        ),
    ]
